name: primer test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: primer test
      run: echo "Primer test"