name: primer test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs: 
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: primer test
      run: echo "Primer test"

    - name: touch file
      run: touch file.txt
    
    - name: Set text
      run: echo "HOLA MUNDO" >> file.txt

    - name: Read File
      run: cat file.txt

  other:
    runs-on: ubuntu-latest

    steps:
    - name: LS
      run: ls -al